//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyberdeckOptionsData
    {
        public CyberdeckOptionsData()
        {
            this.CyberdeckOptionsSkillModifiers = new List<CyberdeckOptionsSkillModifiersData>();
            this.CyberdeckOptionsStatModifiers = new List<CyberdeckOptionsStatModifiersData>();
        }

        public int id { get; set; }
        public string name { get; set; }
        public double CostPerUinitLow { get; set; }
        public double CostPerUinitHigh { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public string Description { get; set; }
        public virtual List<CyberdeckOptionsSkillModifiersData> CyberdeckOptionsSkillModifiers { get; set; }
        public virtual List<CyberdeckOptionsStatModifiersData> CyberdeckOptionsStatModifiers { get; set; }
        public virtual UnitsData Units1 { get; set; }
        
    }
}
