//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerComputerData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerComputerData()
        {
            this.ComputerImprovements = new List<ComputerImprovementsData>();
            this.ComputerPeripherals = new List<ComputerPeripheralsData>();
            this.Program = new List<ProgramData>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> ComputerID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string description { get; set; }
    
        public virtual ComputerData Computer { get; set; }
        public virtual PlayerData Player { get; set; }
        
        public virtual List<ComputerImprovementsData> ComputerImprovements { get; set; }
        
        public virtual List<ComputerPeripheralsData> ComputerPeripherals { get; set; }
        
        public virtual List<ProgramData> Program { get; set; }
    }
}
