//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using CyberpunkServer.Models.DTO;
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCyberdeckImprovementsData
    {
        public int PlayerCyberdeckID { get; set; }
        public int CyberdeckImprovementsID { get; set; }
        public int Quantity { get; set; }
    
        public virtual CyberdeckImprovementsData PlayerCyberdeckImprovements { get; set; }
    }
}
