//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    public partial class PlayerStatModifiersData
    {
        public int id { get; set; }
        public int PlayerStatID { get; set; }
        public string name { get; set; }
        public double amount { get; set; }
    }
}