//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class PlayerSkillData
    {
        public int id { get; set; }
        public Nullable<int> Ranks { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<int> CurrentIP { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> SkillID { get; set; }
    
        [Newtonsoft.Json.JsonIgnore]
        public virtual PlayerData Player { get; set; }
        public virtual SkillData Skill { get; set; }

       
    }
}
