//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlayerCyberdeckData
    {
        public PlayerCyberdeckData()
        {
            this.PlayerCyberdeckImprovements = new List<PlayerCyberdeckImprovementsData>();
            this.PlayerCyberdeckOptions = new List<PlayerCyberdeckOptionsData>();
            this.PlayerCyberdeckPrograms = new List<PlayerCyberdeckProgramsData>();
        }

        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> CyberdeckID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string description { get; set; }
        
        public Dictionary<string, int> Improvements { get; set; }
        public int TotalMemory
        {
            get
            {
                var totalMemory = Cyberdeck?.Memory ?? 0;
                if(Improvements.ContainsKey("Memory"))
                {
                    totalMemory += Improvements["Memory"];
                }
                return totalMemory;
            }
        }
        public int TotalSpeed
        {
            get
            {
                var totalSpeed = Cyberdeck?.Speed ?? 0;
                if (Improvements.ContainsKey("Speed"))
                {
                    totalSpeed += Improvements["Speed"];
                }
                return totalSpeed;
            }
        }
        public int TotalMemoryCost
        {
            get
            {
                return Convert.ToInt32(PlayerCyberdeckPrograms.Sum(x => x.MU ));
            }
        }
        public virtual CyberdeckData Cyberdeck { get; set; }
        public virtual List<PlayerCyberdeckOptionsData> PlayerCyberdeckOptions { get; set; }
        public virtual List<PlayerCyberdeckImprovementsData> PlayerCyberdeckImprovements { get; set; }
        public virtual List<PlayerCyberdeckProgramsData> PlayerCyberdeckPrograms { get; set; }

    }
}
