//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerComputerData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerComputerData()
        {
            this.PlayerComputerImprovements = new List<PlayerComputerImprovementsData>();
            this.PlayerComputerOptions = new List<PlayerComputerOptionsData>();
            this.PlayerComputerPrograms = new List<PlayerComputerProgramsData>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> ComputerID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string description { get; set; }
    
        public virtual ComputerData Computer { get; set; }
        public virtual PlayerData Player { get; set; }
        public bool isCyberEnabled { get; set; }
        public virtual List<PlayerComputerImprovementsData> PlayerComputerImprovements { get; set; }
        public virtual List<PlayerComputerOptionsData> PlayerComputerOptions { get; set; }
        public virtual List<PlayerComputerProgramsData> PlayerComputerPrograms { get; set; }
        
    }
}
