//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;

    public partial class SurgicalCodeData
    {
        
        public SurgicalCodeData()
        {
            
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public string time { get; set; }
        public Nullable<int> NumDamageDice { get; set; }
        public Nullable<int> DamageDiceType { get; set; }
        public Nullable<int> DamageBonus { get; set; }
        public Nullable<int> SurgicalCost { get; set; }
        public Nullable<int> DIFF { get; set; }
        public string Description { get; set; }
    
        
    }
}
