//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class PlayerSkillData
    {
        public int Total
        {
            get
            {
                return Ranks??0 + PlayerSkillModifiers.Sum(x => (int)x.amount);
            }
        }

    }
}
