//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine.UIElements;

    public partial class PlayerData:HasUiElement
    {
        
       
        public PlayerComputerData EquippedComputer { get; set; }
        public PlayerCyberdeckData EquippedCyberdeck { get; set; }
        public VisualElement UIElement { get; set; }
    }
}
