//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CyberpunkServer.Models.DTO;
using System;
using UnityEngine;
using UnityEngine.UIElements;

public interface HasUiElement
{
    VisualElement UIElement { get; set; }
}


namespace CyberpunkServer.Models.DTO
{
    public partial class PlayerCyberdeckProgramsData : HasUiElement, RunningProgram
    {
        public VisualElement UIElement { get; set; }
    }
}