//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine.UIElements;

    public partial class PlayerData:HasUiElement
    {
        
       
        public PlayerComputerData EquippedComputer { get; set; }
        public PlayerCyberdeckData EquippedCyberdeck { get; set; }
        public VisualElement UIElement { get; set; }
        public int BTM
        {
            get
            {
                int btm = 0;
                var body = StatLookup["BT"].Total;
                if (body <= 2)
                {
                    btm = 0;
                }
                else if (body <= 4)
                {
                    btm = -1;
                }
                else if (body <= 7)
                {
                    btm = -2;
                }
                else if (body <= 9)
                {
                    btm = -3;
                }
                else if (body == 10)
                {
                    btm = -4;
                }
                return btm;
            }
        }
    }
}
