//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine.UIElements;

namespace CyberpunkServer.Models.DTO
{
    public partial class PlayerComputerProgramsData : HasUiElement, RunningProgram
    {
        public VisualElement UIElement { get; set; }
        public int? OwnerID { get; set; }
        public int xPos { get; set; }
        public int yPos { get; set; }
        public int DeviceID
        {
            get
            {
                return PlayerComputerID.Value;
            }
            set
            {

            }
        }
        public string DeviceType { get; set; } = "Computer";
    }
}