//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ArmorLocationsData: iConvert
    {
        public static ICollection<CyberpunkServer.Models.ArmorLocations> CopyProperties(ICollection<ArmorLocationsData> orig, ICollection<CyberpunkServer.Models.ArmorLocations> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.ArmorLocations> dictionary1 = new Dictionary<int, CyberpunkServer.Models.ArmorLocations>();
                Dictionary<int, ArmorLocationsData> dictionary2 = new Dictionary<int, ArmorLocationsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        ArmorLocationsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.ArmorLocations();
                        dest.Add(ArmorLocationsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.ArmorLocations> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<ArmorLocationsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator ArmorLocationsData(CyberpunkServer.Models.ArmorLocations ArmorLocations)
        {
            var ret = Converter<ArmorLocationsData, Models.ArmorLocations>.ConvertType(ArmorLocations, new ArmorLocationsData());
            return ret;
        }

        public static List<ArmorLocationsData> ConvertList(ICollection<CyberpunkServer.Models.ArmorLocations> origs)
        {

            var ret = Converter<ArmorLocationsData, ArmorLocations>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.ArmorLocations CopyProperties(ArmorLocationsData ArmorLocations, Models.ArmorLocations dest, CyberpunkEntities db)
        {
            Converter<ArmorLocationsData, ArmorLocations>.ConvertType<ArmorLocationsData>(ArmorLocations, dest, "CopyProperties");
            return dest;
        }

    }
}
