//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerPeripheralsData : iConvert
    {
        public static explicit operator ComputerPeripheralsData(CyberpunkServer.Models.ComputerPeripherals ComputerPeripherals)
        {
            var ret = Converter<ComputerPeripheralsData, Models.ComputerPeripherals>.ConvertType(ComputerPeripherals, new ComputerPeripheralsData());
            return ret;
        }

        public static List<ComputerPeripheralsData> ConvertList(ICollection<CyberpunkServer.Models.ComputerPeripherals> origs)
        {

            var ret = Converter<ComputerPeripheralsData, ComputerPeripherals>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.ComputerPeripherals CopyProperties(ComputerPeripheralsData ComputerPeripherals, Models.ComputerPeripherals dest, CyberpunkEntities db)
        {
            Converter<ComputerPeripheralsData, ComputerPeripherals>.ConvertType<ComputerPeripheralsData>(ComputerPeripherals, dest, "CopyProperties");
            return dest;
        }


    }
}
