//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerPeripheralSkillModifiersData : iConvert
    {
        public static explicit operator ComputerPeripheralSkillModifiersData(CyberpunkServer.Models.ComputerPeripheralSkillModifiers ComputerPeripheralSkillModifiers)
        {
            var ret = Converter<ComputerPeripheralSkillModifiersData, Models.ComputerPeripheralSkillModifiers>.ConvertType(ComputerPeripheralSkillModifiers, new ComputerPeripheralSkillModifiersData());
            return ret;
        }

        public static List<ComputerPeripheralSkillModifiersData> ConvertList(ICollection<CyberpunkServer.Models.ComputerPeripheralSkillModifiers> origs)
        {

            var ret = Converter<ComputerPeripheralSkillModifiersData, ComputerPeripheralSkillModifiers>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.ComputerPeripheralSkillModifiers CopyProperties(ComputerPeripheralSkillModifiersData ComputerPeripheralSkillModifiers, Models.ComputerPeripheralSkillModifiers dest, CyberpunkEntities db)
        {
            Converter<ComputerPeripheralSkillModifiersData, ComputerPeripheralSkillModifiers>.ConvertType<ComputerPeripheralSkillModifiersData>(ComputerPeripheralSkillModifiers, dest, "CopyProperties");
            return dest;
        }

    }
}
