//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyberdeckData : iConvert
    {
        public static explicit operator CyberdeckData(CyberpunkServer.Models.Cyberdeck Cyberdeck)
        {
            var ret = Converter<CyberdeckData, Models.Cyberdeck>.ConvertType(Cyberdeck, new CyberdeckData());
            return ret;
        }

        public static List<CyberdeckData> ConvertList(ICollection<CyberpunkServer.Models.Cyberdeck> origs)
        {

            var ret = Converter<CyberdeckData, Cyberdeck>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.Cyberdeck CopyProperties(CyberdeckData Cyberdeck, Models.Cyberdeck dest, CyberpunkEntities db)
        {
            Converter<CyberdeckData, Cyberdeck>.ConvertType<CyberdeckData>(Cyberdeck, dest, "CopyProperties");
            return dest;
        }


    }
}
