//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyberdeckOptionsStatModifiersData : iConvert
    {
        public static explicit operator CyberdeckOptionsStatModifiersData(CyberpunkServer.Models.CyberdeckOptionsStatModifiers CyberdeckOptionsStatModifiers)
        {
            var ret = Converter<CyberdeckOptionsStatModifiersData, Models.CyberdeckOptionsStatModifiers>.ConvertType(CyberdeckOptionsStatModifiers, new CyberdeckOptionsStatModifiersData());
            return ret;
        }

        public static List<CyberdeckOptionsStatModifiersData> ConvertList(ICollection<CyberpunkServer.Models.CyberdeckOptionsStatModifiers> origs)
        {

            var ret = Converter<CyberdeckOptionsStatModifiersData, CyberdeckOptionsStatModifiers>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.CyberdeckOptionsStatModifiers CopyProperties(CyberdeckOptionsStatModifiersData CyberdeckOptionsStatModifiers, Models.CyberdeckOptionsStatModifiers dest, CyberpunkEntities db)
        {
            Converter<CyberdeckOptionsStatModifiersData, CyberdeckOptionsStatModifiers>.ConvertType<CyberdeckOptionsStatModifiersData>(CyberdeckOptionsStatModifiers, dest, "CopyProperties");
            return dest;
        }

    }
}
