//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;
    public partial class FortressWallsData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.FortressWalls> CopyProperties(ICollection<FortressWallsData> orig, ICollection<CyberpunkServer.Models.FortressWalls> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.FortressWalls> dictionary1 = new Dictionary<int, CyberpunkServer.Models.FortressWalls>();
                Dictionary<int, FortressWallsData> dictionary2 = new Dictionary<int, FortressWallsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        FortressWallsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.FortressWalls();
                        dest.Add(FortressWallsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.FortressWalls> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<FortressWallsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator FortressWallsData(CyberpunkServer.Models.FortressWalls FortressWalls)
        {
            var ret = Converter<FortressWallsData, Models.FortressWalls>.ConvertType(FortressWalls, new FortressWallsData());
            return ret;
        }

        public static List<FortressWallsData> ConvertList(ICollection<CyberpunkServer.Models.FortressWalls> origs)
        {

            var ret = Converter<FortressWallsData, FortressWalls>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.FortressWalls CopyProperties(FortressWallsData FortressWalls, Models.FortressWalls dest, CyberpunkEntities db)
        {
            Converter<FortressWallsData, FortressWalls>.ConvertType<FortressWallsData>(FortressWalls, dest, "CopyProperties");
            return dest;
        }

    }

}
