//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FortressData
    {

        public static ICollection<FortressData> ConvertList(ICollection<CyberpunkServer.Models.Fortress> origs)
        {
            var ret = new HashSet<FortressData>();
            foreach (var orig in origs)
            {
                var dest = new FortressData();
                dest.subgridID = orig.subgridID;
                dest.WallStrength = orig.WallStrength;
                dest.Int = orig.Int;
                dest.id = orig.id;
                dest.FortressCPU = DTO.FortressCPUData.ConvertList(orig.FortressCPU).ToList();
                dest.FortressCodeGates = DTO.FortressCodeGatesData.ConvertList(orig.FortressCodeGates).ToList();
                dest.FortressMemory = DTO.FortressMemoryData.ConvertList(orig.FortressMemory).ToList();
                dest.FortressWalls = DTO.FortressWallsData.ConvertList(orig.FortressWalls).ToList();
                ret.Add(dest);
            }
            return ret;
        }
        public static ICollection<CyberpunkServer.Models.Fortress> CopyProperties(ICollection<FortressData> orig, ICollection<CyberpunkServer.Models.Fortress> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.Fortress> dictionary1 = new Dictionary<int, CyberpunkServer.Models.Fortress>();
                Dictionary<int, FortressData> dictionary2 = new Dictionary<int, FortressData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        FortressData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.Fortress();
                        dest.Add(FortressData.CopyProperties(orig1, dest2, db));
                    }
                    dictionary2.Add(orig1.id, orig1);
                }
                foreach (KeyValuePair<int, Models.Fortress> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<FortressData>())
                dest.Clear();
            return dest;
        }
        public static CyberpunkServer.Models.Fortress CopyProperties(FortressData orig, CyberpunkServer.Models.Fortress dest, CyberpunkEntities db)
        {
            dest.subgridID = orig.subgridID;
            dest.WallStrength = orig.WallStrength;
            dest.Int = orig.Int;
            dest.id = orig.id;
            DTO.FortressCPUData.CopyProperties(orig.FortressCPU, dest.FortressCPU, db);
            DTO.FortressCodeGatesData.CopyProperties(orig.FortressCodeGates, dest.FortressCodeGates, db);
            DTO.FortressMemoryData.CopyProperties(orig.FortressMemory, dest.FortressMemory, db);
            DTO.FortressWallsData.CopyProperties(orig.FortressWalls, dest.FortressWalls, db);
            DTO.FortressRemotesData.CopyProperties(orig.FortressRemotes, dest.FortressRemotes, db);
            return dest;
        }
    }
}
