//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FortressSkillsData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.FortressSkills> CopyProperties(ICollection<FortressSkillsData> orig, ICollection<CyberpunkServer.Models.FortressSkills> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.FortressSkills> dictionary1 = new Dictionary<int, CyberpunkServer.Models.FortressSkills>();
                Dictionary<int, FortressSkillsData> dictionary2 = new Dictionary<int, FortressSkillsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        FortressSkillsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.FortressSkills();
                        dest.Add(FortressSkillsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.FortressSkills> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<FortressSkillsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator FortressSkillsData(CyberpunkServer.Models.FortressSkills FortressSkills)
        {
            var ret = Converter<FortressSkillsData, Models.FortressSkills>.ConvertType(FortressSkills, new FortressSkillsData());
            return ret;
        }

        public static List<FortressSkillsData> ConvertList(ICollection<CyberpunkServer.Models.FortressSkills> origs)
        {

            var ret = Converter<FortressSkillsData, FortressSkills>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.FortressSkills CopyProperties(FortressSkillsData FortressSkills, Models.FortressSkills dest, CyberpunkEntities db)
        {
            Converter<FortressSkillsData, FortressSkills>.ConvertType<FortressSkillsData>(FortressSkills, dest, "CopyProperties");
            return dest;
        }

    }
}
