//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;

    public partial class NetObjTypeData
    {
        public static explicit operator NetObjTypeData(CyberpunkServer.Models.NetObjType player)
        {
            var ret = new NetObjTypeData
            {
                id = player.id,
                Name=player.Name,
                Title=player.Title,
                SVG=player.SVG
                
            };
            
            return ret;
        }
        public static ICollection<NetObjTypeData> ConvertList(ICollection<CyberpunkServer.Models.NetObjType> origs)
        {
            var ret = new HashSet<NetObjTypeData>();
            foreach (var orig in origs)
            {
                var dest = (NetObjTypeData)orig;
                ret.Add(dest);
            }
            return ret;
        }
    }
}
