//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace CyberpunkServer.Models.DTO
{
    public partial class PlayerComputerOptionsData: iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerComputerOptions> CopyProperties(ICollection<PlayerComputerOptionsData> orig, ICollection<CyberpunkServer.Models.PlayerComputerOptions> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerComputerOptions> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerComputerOptions>();
                Dictionary<int, PlayerComputerOptionsData> dictionary2 = new Dictionary<int, PlayerComputerOptionsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerComputerOptionsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerComputerOptions();
                        dest.Add(PlayerComputerOptionsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerComputerOptions> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerComputerOptionsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerComputerOptionsData(CyberpunkServer.Models.PlayerComputerOptions PlayerComputerOptions)
        {
            var ret = Converter<PlayerComputerOptionsData, Models.PlayerComputerOptions>.ConvertType(PlayerComputerOptions, new PlayerComputerOptionsData());
            return ret;
        }

        public static List<PlayerComputerOptionsData> ConvertList(ICollection<CyberpunkServer.Models.PlayerComputerOptions> origs)
        {

            var ret = Converter<PlayerComputerOptionsData, PlayerComputerOptions>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerComputerOptions CopyProperties(PlayerComputerOptionsData PlayerComputerOptions, Models.PlayerComputerOptions dest, CyberpunkEntities db)
        {
            Converter<PlayerComputerOptionsData, PlayerComputerOptions>.ConvertType<PlayerComputerOptionsData>(PlayerComputerOptions, dest, "CopyProperties");
            return dest;
        }


    }
}