//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class PlayerSkillModifiersData:iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerSkillModifiers> CopyProperties(ICollection<PlayerSkillModifiersData> orig, ICollection<CyberpunkServer.Models.PlayerSkillModifiers> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerSkillModifiers> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerSkillModifiers>();
                Dictionary<int, PlayerSkillModifiersData> dictionary2 = new Dictionary<int, PlayerSkillModifiersData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerSkillModifiersData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerSkillModifiers();
                        dest.Add(PlayerSkillModifiersData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerSkillModifiers> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerSkillModifiersData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerSkillModifiersData(CyberpunkServer.Models.PlayerSkillModifiers PlayerSkillModifiers)
        {
            var ret = Converter<PlayerSkillModifiersData, Models.PlayerSkillModifiers>.ConvertType(PlayerSkillModifiers, new PlayerSkillModifiersData());
            return ret;
        }

        public static List<PlayerSkillModifiersData> ConvertList(ICollection<CyberpunkServer.Models.PlayerSkillModifiers> origs)
        {

            var ret = Converter<PlayerSkillModifiersData, PlayerSkillModifiers>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerSkillModifiers CopyProperties(PlayerSkillModifiersData PlayerSkillModifiers, Models.PlayerSkillModifiers dest, CyberpunkEntities db)
        {
            Converter<PlayerSkillModifiersData, PlayerSkillModifiers>.ConvertType<PlayerSkillModifiersData>(PlayerSkillModifiers, dest, "CopyProperties");
            return dest;
        }

    }
}