//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;

    public partial class PlayerWeaponData
    {
      
        public static ICollection<PlayerWeaponData> ConvertList(ICollection<CyberpunkServer.Models.PlayerWeapon> origs)
        {
            var ret = new HashSet<PlayerWeaponData>();
            foreach (var orig in origs)
            {
                var dest = new PlayerWeaponData();
                dest.id = orig.id;
                dest.WeaponID = orig.WeaponID;
                dest.PlayerID = orig.PlayerID;
                ret.Add(dest);
            }
            return ret;
        }
        public static ICollection<CyberpunkServer.Models.PlayerWeapon> CopyProperties(ICollection<PlayerWeaponData> orig, ICollection<CyberpunkServer.Models.PlayerWeapon> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerWeapon> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerWeapon>();
                Dictionary<int, PlayerWeaponData> dictionary2 = new Dictionary<int, PlayerWeaponData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerWeaponData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerWeapon();
                        dest.Add(PlayerWeaponData.CopyProperties(orig1, dest2, db));
                    }
                    dictionary2.Add(orig1.id, orig1);
                }
                foreach (KeyValuePair<int, Models.PlayerWeapon> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerWeaponData>())
                dest.Clear();
            return dest;
        }
        public static CyberpunkServer.Models.PlayerWeapon CopyProperties(PlayerWeaponData orig, CyberpunkServer.Models.PlayerWeapon dest, CyberpunkEntities db)
        {
            dest.id = orig.id;
            dest.WeaponID = orig.WeaponID;
            dest.PlayerID = orig.PlayerID;
            return null;
        }
    }
}
