//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlayerCyberdeckData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerCyberdeck> CopyProperties(ICollection<PlayerCyberdeckData> orig, ICollection<CyberpunkServer.Models.PlayerCyberdeck> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerCyberdeck> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerCyberdeck>();
                Dictionary<int, PlayerCyberdeckData> dictionary2 = new Dictionary<int, PlayerCyberdeckData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerCyberdeckData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerCyberdeck();
                        dest.Add(PlayerCyberdeckData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerCyberdeck> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerCyberdeckData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerCyberdeckData(CyberpunkServer.Models.PlayerCyberdeck PlayerCyberdeck)
        {
            var ret = Converter<PlayerCyberdeckData, Models.PlayerCyberdeck>.ConvertType(PlayerCyberdeck, new PlayerCyberdeckData());
            ret.Improvements= ret.PlayerCyberdeckImprovements.ToDictionary(x => x.CyberdeckImprovements.ImprovementFor, x => x.CyberdeckImprovements.ImprovementAmount * x.Quantity ?? 1);
            return ret;
        }

        public static List<PlayerCyberdeckData> ConvertList(ICollection<CyberpunkServer.Models.PlayerCyberdeck> origs)
        {

            var ret = Converter<PlayerCyberdeckData, PlayerCyberdeck>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerCyberdeck CopyProperties(PlayerCyberdeckData PlayerCyberdeck, Models.PlayerCyberdeck dest, CyberpunkEntities db)
        {
            Converter<PlayerCyberdeckData, PlayerCyberdeck>.ConvertType<PlayerCyberdeckData>(PlayerCyberdeck, dest, "CopyProperties");
            return dest;
        }

    }
}
