//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class PlayerStatModifiersData:iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerStatModifiers> CopyProperties(ICollection<PlayerStatModifiersData> orig, ICollection<CyberpunkServer.Models.PlayerStatModifiers> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerStatModifiers> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerStatModifiers>();
                Dictionary<int, PlayerStatModifiersData> dictionary2 = new Dictionary<int, PlayerStatModifiersData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerStatModifiersData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerStatModifiers();
                        dest.Add(PlayerStatModifiersData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerStatModifiers> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerStatModifiersData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerStatModifiersData(CyberpunkServer.Models.PlayerStatModifiers PlayerStatModifiers)
        {
            var ret = Converter<PlayerStatModifiersData, Models.PlayerStatModifiers>.ConvertType(PlayerStatModifiers, new PlayerStatModifiersData());
            return ret;
        }

        public static List<PlayerStatModifiersData> ConvertList(ICollection<CyberpunkServer.Models.PlayerStatModifiers> origs)
        {

            var ret = Converter<PlayerStatModifiersData, PlayerStatModifiers>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerStatModifiers CopyProperties(PlayerStatModifiersData PlayerStatModifiers, Models.PlayerStatModifiers dest, CyberpunkEntities db)
        {
            Converter<PlayerStatModifiersData, PlayerStatModifiers>.ConvertType<PlayerStatModifiersData>(PlayerStatModifiers, dest, "CopyProperties");
            return dest;
        }

    }
}