//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;

    public partial class PlayerArmorData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerArmor> CopyProperties(ICollection<PlayerArmorData> orig, ICollection<CyberpunkServer.Models.PlayerArmor> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerArmor> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerArmor>();
                Dictionary<int, PlayerArmorData> dictionary2 = new Dictionary<int, PlayerArmorData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerArmorData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerArmor();
                        dest.Add(PlayerArmorData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerArmor> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerArmorData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerArmorData(CyberpunkServer.Models.PlayerArmor PlayerArmor)
        {
            var ret = Converter<PlayerArmorData, Models.PlayerArmor>.ConvertType(PlayerArmor, new PlayerArmorData());
            return ret;
        }

        public static List<PlayerArmorData> ConvertList(ICollection<CyberpunkServer.Models.PlayerArmor> origs)
        {

            var ret = Converter<PlayerArmorData, PlayerArmor>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerArmor CopyProperties(PlayerArmorData PlayerArmor, Models.PlayerArmor dest, CyberpunkEntities db)
        {
            Converter<PlayerArmorData, PlayerArmor>.ConvertType<PlayerArmorData>(PlayerArmor, dest, "CopyProperties");
            return dest;
        }

    }
}
