//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;

    public partial class PlayerStatData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerStat> CopyProperties(ICollection<PlayerStatData> orig, ICollection<CyberpunkServer.Models.PlayerStat> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerStat> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerStat>();
                Dictionary<int, PlayerStatData> dictionary2 = new Dictionary<int, PlayerStatData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerStatData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerStat();
                        dest.Add(PlayerStatData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerStat> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerStatData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerStatData(CyberpunkServer.Models.PlayerStat PlayerStat)
        {
            var ret = Converter<PlayerStatData, Models.PlayerStat>.ConvertType(PlayerStat, new PlayerStatData());
            return ret;
        }

        public static List<PlayerStatData> ConvertList(ICollection<CyberpunkServer.Models.PlayerStat> origs)
        {

            var ret = Converter<PlayerStatData, PlayerStat>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerStat CopyProperties(PlayerStatData PlayerStat, Models.PlayerStat dest, CyberpunkEntities db)
        {
            Converter<PlayerStatData, PlayerStat>.ConvertType<PlayerStatData>(PlayerStat, dest, "CopyProperties");
            return dest;
        }

    }
}