//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProgramFunctionsData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.ProgramFunctions> CopyProperties(ICollection<ProgramFunctionsData> orig, ICollection<CyberpunkServer.Models.ProgramFunctions> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.ProgramFunctions> dictionary1 = new Dictionary<int, CyberpunkServer.Models.ProgramFunctions>();
                Dictionary<int, ProgramFunctionsData> dictionary2 = new Dictionary<int, ProgramFunctionsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        ProgramFunctionsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.ProgramFunctions();
                        dest.Add(ProgramFunctionsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.ProgramFunctions> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<ProgramFunctionsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator ProgramFunctionsData(CyberpunkServer.Models.ProgramFunctions ProgramFunctions)
        {
            var ret = Converter<ProgramFunctionsData, Models.ProgramFunctions>.ConvertType(ProgramFunctions, new ProgramFunctionsData());
            return ret;
        }

        public static List<ProgramFunctionsData> ConvertList(ICollection<CyberpunkServer.Models.ProgramFunctions> origs)
        {

            var ret = Converter<ProgramFunctionsData, ProgramFunctions>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.ProgramFunctions CopyProperties(ProgramFunctionsData ProgramFunctions, Models.ProgramFunctions dest, CyberpunkEntities db)
        {
            Converter<ProgramFunctionsData, ProgramFunctions>.ConvertType<ProgramFunctionsData>(ProgramFunctions, dest, "CopyProperties");
            return dest;
        }

    }
}