//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;

    public partial class SkillTypesData
    {
       
        public static explicit operator SkillTypesData(CyberpunkServer.Models.SkillTypes orig)
        {
            var dest = new SkillTypesData();
            dest.id = orig.id;
            dest.Name = orig.Name;
            return dest;
        }
    }
}
