//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;

    public partial class SkillData
    {
        
        public static explicit operator SkillData(CyberpunkServer.Models.Skill orig)
        {
            var dest = new SkillData();
            dest.id = orig.id;
            dest.Name = orig.Name;
            dest.SkillType = orig.SkillType;
            dest.StatID = orig.StatID;
            dest.Description = orig.Description;
            dest.Multiplier = orig.Multiplier;
            dest.SkillTypes = (SkillTypesData)orig.SkillTypes;
            return dest;
        }
    }
}
