//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SkillData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.Skill> CopyProperties(ICollection<SkillData> orig, ICollection<CyberpunkServer.Models.Skill> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.Skill> dictionary1 = new Dictionary<int, CyberpunkServer.Models.Skill>();
                Dictionary<int, SkillData> dictionary2 = new Dictionary<int, SkillData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        SkillData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.Skill();
                        dest.Add(SkillData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.Skill> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<SkillData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator SkillData(CyberpunkServer.Models.Skill Skill)
        {
            var ret = Converter<SkillData, Models.Skill>.ConvertType(Skill, new SkillData());
            return ret;
        }

        public static List<SkillData> ConvertList(ICollection<CyberpunkServer.Models.Skill> origs)
        {

            var ret = Converter<SkillData, Skill>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.Skill CopyProperties(SkillData Skill, Models.Skill dest, CyberpunkEntities db)
        {
            Converter<SkillData, Skill>.ConvertType<SkillData>(Skill, dest, "CopyProperties");
            return dest;
        }

    }
}