//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WeaponConcTypesData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.WeaponConcTypes> CopyProperties(ICollection<WeaponConcTypesData> orig, ICollection<CyberpunkServer.Models.WeaponConcTypes> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.WeaponConcTypes> dictionary1 = new Dictionary<int, CyberpunkServer.Models.WeaponConcTypes>();
                Dictionary<int, WeaponConcTypesData> dictionary2 = new Dictionary<int, WeaponConcTypesData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        WeaponConcTypesData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.WeaponConcTypes();
                        dest.Add(WeaponConcTypesData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.WeaponConcTypes> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<WeaponConcTypesData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator WeaponConcTypesData(CyberpunkServer.Models.WeaponConcTypes WeaponConcTypes)
        {
            var ret = Converter<WeaponConcTypesData, Models.WeaponConcTypes>.ConvertType(WeaponConcTypes, new WeaponConcTypesData());
            return ret;
        }

        public static List<WeaponConcTypesData> ConvertList(ICollection<CyberpunkServer.Models.WeaponConcTypes> origs)
        {

            var ret = Converter<WeaponConcTypesData, WeaponConcTypes>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.WeaponConcTypes CopyProperties(WeaponConcTypesData WeaponConcTypes, Models.WeaponConcTypes dest, CyberpunkEntities db)
        {
            Converter<WeaponConcTypesData, WeaponConcTypes>.ConvertType<WeaponConcTypesData>(WeaponConcTypes, dest, "CopyProperties");
            return dest;
        }

    }
}