//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;

    public partial class FortressData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FortressData()
        {
            this.FortressCPU = new HashSet<FortressCPUData>();
            this.FortressCodeGates = new HashSet<FortressCodeGatesData>();
            this.FortressMemory = new HashSet<FortressMemoryData>();
            this.FortressWalls = new HashSet<FortressWallsData>();
        }
    
        public int id { get; set; }
        public Nullable<int> subgridID { get; set; }
        public Nullable<int> WallStrength { get; set; }
        public Nullable<int> Int { get; set; }
    
        public virtual SubgridData Subgrid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FortressCPUData> FortressCPU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FortressCodeGatesData> FortressCodeGates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FortressMemoryData> FortressMemory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FortressWallsData> FortressWalls { get; set; }

       
    }
}
