//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using Cyberpunk_Server_Blazor.Pages.Subgird;
	
	using System;
    using System.Collections.Generic;
    using System.Linq;
	using System.Text.Json.Serialization;

	public partial interface NetItem
	{
		[JsonIgnore]
		Tile CurrentTile { get; set; }
	}

	public partial class FortressCodeGatesData: NetItem
	{
        [Newtonsoft.Json.JsonIgnore]
        [JsonIgnore]
        public Tile CurrentTile { get; set; }
	}
}
