//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Cyberpunk_Server_Blazor.Pages.Subgird;
using System;
using System.Text.Json.Serialization;

namespace CyberpunkServer.Models.DTO
{
    public partial class PlayerComputerProgramsData: RunningProgram
	{
        [JsonIgnore]
        public Tile CurrentTile { get; set; }
    }
}