//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerPeripherals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComputerPeripherals()
        {
            this.ComputerPeripheralSkillModifiers = new HashSet<ComputerPeripheralSkillModifiers>();
            this.ComputerPeripheralStatModifiers = new HashSet<ComputerPeripheralStatModifiers>();
            this.PlayerComputer = new HashSet<PlayerComputer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double CostPerUinitLow { get; set; }
        public double CostPerUinitHigh { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public int Units { get; set; }
        public double CostPerUnitLow { get; set; }
        public double CostPerUnitHigh { get; set; }
        public Nullable<int> MU { get; set; }
        public Nullable<int> Bonus { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputerPeripheralSkillModifiers> ComputerPeripheralSkillModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputerPeripheralStatModifiers> ComputerPeripheralStatModifiers { get; set; }
        public virtual Units Units1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerComputer> PlayerComputer { get; set; }
    }
}
