//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerPeripheralStatModifiers
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> StatID { get; set; }
        public int Modifier { get; set; }
        public Nullable<int> ComputerPeripheralID { get; set; }
    
        public virtual ComputerPeripherals ComputerPeripherals { get; set; }
        public virtual Stat Stat { get; set; }
    }
}
