//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computer()
        {
            this.PlayerComputer = new HashSet<PlayerComputer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int Memory { get; set; }
        public int Speed { get; set; }
        public int Int { get; set; }
        public int NumCPU { get; set; }
        public bool IsPortable { get; set; }
        public bool IsCyberAvailable { get; set; }
        public double BateryHours { get; set; }
        public int WallStrength { get; set; }
        public double PriceLow { get; set; }
        public double PriceHigh { get; set; }
        public int NumSlots { get; set; }
        public int Chipslots { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerComputer> PlayerComputer { get; set; }
    }
}
