//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyberdeck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cyberdeck()
        {
            this.PlayerCyberdeck = new HashSet<PlayerCyberdeck>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int Memory { get; set; }
        public int Speed { get; set; }
        public int WallStrength { get; set; }
        public double PriceLow { get; set; }
        public double PriceHigh { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCyberdeck> PlayerCyberdeck { get; set; }
    }
}
