//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyberdeckOptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CyberdeckOptions()
        {
            this.CyberdeckOptionsSkillModifiers = new HashSet<CyberdeckOptionsSkillModifiers>();
            this.CyberdeckOptionsStatModifiers = new HashSet<CyberdeckOptionsStatModifiers>();
            this.PlayerCyberdeck = new HashSet<PlayerCyberdeck>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double CostPerUinitLow { get; set; }
        public double CostPerUinitHigh { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public int Units { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CyberdeckOptionsSkillModifiers> CyberdeckOptionsSkillModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CyberdeckOptionsStatModifiers> CyberdeckOptionsStatModifiers { get; set; }
        public virtual Units Units1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCyberdeck> PlayerCyberdeck { get; set; }
    }
}
