//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCyberdeck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerCyberdeck()
        {
            this.CyberdeckImprovements = new HashSet<CyberdeckImprovements>();
            this.CyberdeckOptions = new HashSet<CyberdeckOptions>();
            this.Program = new HashSet<Program>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> CyberdeckID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string description { get; set; }
    
        public virtual Cyberdeck Cyberdeck { get; set; }
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CyberdeckImprovements> CyberdeckImprovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CyberdeckOptions> CyberdeckOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Program { get; set; }
    }
}
