//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerStat()
        {
            this.PlayerStatModifiers = new HashSet<PlayerStatModifiers>();
        }
    
        public int id { get; set; }
        public Nullable<int> StatID { get; set; }
        public Nullable<int> Base { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<int> Current { get; set; }
        public Nullable<int> PlayerID { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Stat Stat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerStatModifiers> PlayerStatModifiers { get; set; }
    }
}
