//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Weapons()
        {
            this.PlayerWeapon = new HashSet<PlayerWeapon>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumDice { get; set; }
        public Nullable<int> DiceType { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<int> ROF { get; set; }
        public Nullable<int> REL { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Conc { get; set; }
        public Nullable<int> Shots1 { get; set; }
        public Nullable<int> Shots2 { get; set; }
        public Nullable<int> Range { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerWeapon> PlayerWeapon { get; set; }
        public virtual WeaponConcTypes WeaponConcTypes { get; set; }
        public virtual WeaponTypes WeaponTypes { get; set; }
    }
}
