//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ComputerData : iConvert
    {

        public static explicit operator ComputerData(CyberpunkServer.Models.Computer Computer)
        {
            var ret = Converter<ComputerData, Models.Computer>.ConvertType(Computer, new ComputerData());
            return ret;
        }

        public static List<ComputerData> ConvertList(ICollection<CyberpunkServer.Models.Computer> origs)
        {

            var ret = Converter<ComputerData, Computer>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.Computer CopyProperties(ComputerData Computer, Models.Computer dest, CyberpunkEntities db)
        {
            Converter<ComputerData, Computer>.ConvertType<ComputerData>(Computer, dest, "CopyProperties");
            return dest;
        }


    }
}
