//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerImprovementsData : iConvert
    {
        public static explicit operator ComputerImprovementsData(CyberpunkServer.Models.ComputerImprovements ComputerImprovements)
        {
            var ret = Converter<ComputerImprovementsData, Models.ComputerImprovements>.ConvertType(ComputerImprovements, new ComputerImprovementsData());
            
            return ret;
        }

        public static List<ComputerImprovementsData> ConvertList(ICollection<CyberpunkServer.Models.ComputerImprovements> origs)
        {

            var ret = Converter<ComputerImprovementsData, ComputerImprovements>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.ComputerImprovements CopyProperties(ComputerImprovementsData ComputerImprovements, Models.ComputerImprovements dest, CyberpunkEntities db)
        {
            Converter<ComputerImprovementsData, ComputerImprovements>.ConvertType<ComputerImprovementsData>(ComputerImprovements, dest, "CopyProperties");
            return dest;
        }


    }
}
