//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerPeripheralStatModifiersData : iConvert
    {
        public static explicit operator ComputerPeripheralStatModifiersData(CyberpunkServer.Models.ComputerPeripheralStatModifiers ComputerPeripheralStatModifiers)
        {
            var ret = Converter<ComputerPeripheralStatModifiersData, Models.ComputerPeripheralStatModifiers>.ConvertType(ComputerPeripheralStatModifiers, new ComputerPeripheralStatModifiersData());
            return ret;
        }

        public static List<ComputerPeripheralStatModifiersData> ConvertList(ICollection<CyberpunkServer.Models.ComputerPeripheralStatModifiers> origs)
        {

            var ret = Converter<ComputerPeripheralStatModifiersData, ComputerPeripheralStatModifiers>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.ComputerPeripheralStatModifiers CopyProperties(ComputerPeripheralStatModifiersData ComputerPeripheralStatModifiers, Models.ComputerPeripheralStatModifiers dest, CyberpunkEntities db)
        {
            Converter<ComputerPeripheralStatModifiersData, ComputerPeripheralStatModifiers>.ConvertType<ComputerPeripheralStatModifiersData>(ComputerPeripheralStatModifiers, dest, "CopyProperties");
            return dest;
        }

    }
}
