//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;
    public partial class FortressMemoryData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.FortressMemory> CopyProperties(ICollection<FortressMemoryData> orig, ICollection<CyberpunkServer.Models.FortressMemory> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.FortressMemory> dictionary1 = new Dictionary<int, CyberpunkServer.Models.FortressMemory>();
                Dictionary<int, FortressMemoryData> dictionary2 = new Dictionary<int, FortressMemoryData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        FortressMemoryData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.FortressMemory();
                        dest.Add(FortressMemoryData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.FortressMemory> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<FortressMemoryData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator FortressMemoryData(CyberpunkServer.Models.FortressMemory FortressMemory)
        {
            var ret = Converter<FortressMemoryData, Models.FortressMemory>.ConvertType(FortressMemory, new FortressMemoryData());
            return ret;
        }

        public static List<FortressMemoryData> ConvertList(ICollection<CyberpunkServer.Models.FortressMemory> origs)
        {

            var ret = Converter<FortressMemoryData, FortressMemory>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.FortressMemory CopyProperties(FortressMemoryData FortressMemory, Models.FortressMemory dest, CyberpunkEntities db)
        {
            Converter<FortressMemoryData, FortressMemory>.ConvertType<FortressMemoryData>(FortressMemory, dest, "CopyProperties");
            return dest;
        }

    }

}
