//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FortressData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.Fortress> CopyProperties(ICollection<FortressData> orig, ICollection<CyberpunkServer.Models.Fortress> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.Fortress> dictionary1 = new Dictionary<int, CyberpunkServer.Models.Fortress>();
                Dictionary<int, FortressData> dictionary2 = new Dictionary<int, FortressData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        FortressData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.Fortress();
                        dest.Add(FortressData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.Fortress> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<FortressData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator FortressData(CyberpunkServer.Models.Fortress Fortress)
        {
            var ret = Converter<FortressData, Models.Fortress>.ConvertType(Fortress, new FortressData());
            return ret;
        }

        public static List<FortressData> ConvertList(ICollection<CyberpunkServer.Models.Fortress> origs)
        {

            var ret = Converter<FortressData, Fortress>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.Fortress CopyProperties(FortressData Fortress, Models.Fortress dest, CyberpunkEntities db)
        {
            Converter<FortressData, Fortress>.ConvertType<FortressData>(Fortress, dest, "CopyProperties");
            return dest;
        }

    }
}
