//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;
    public partial class FortressCPUData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.FortressCPU> CopyProperties(ICollection<FortressCPUData> orig, ICollection<CyberpunkServer.Models.FortressCPU> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.FortressCPU> dictionary1 = new Dictionary<int, CyberpunkServer.Models.FortressCPU>();
                Dictionary<int, FortressCPUData> dictionary2 = new Dictionary<int, FortressCPUData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        FortressCPUData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.FortressCPU();
                        dest.Add(FortressCPUData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.FortressCPU> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<FortressCPUData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator FortressCPUData(CyberpunkServer.Models.FortressCPU FortressCPU)
        {
            var ret = Converter<FortressCPUData, Models.FortressCPU>.ConvertType(FortressCPU, new FortressCPUData());
            return ret;
        }

        public static List<FortressCPUData> ConvertList(ICollection<CyberpunkServer.Models.FortressCPU> origs)
        {

            var ret = Converter<FortressCPUData, FortressCPU>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.FortressCPU CopyProperties(FortressCPUData FortressCPU, Models.FortressCPU dest, CyberpunkEntities db)
        {
            Converter<FortressCPUData, FortressCPU>.ConvertType<FortressCPUData>(FortressCPU, dest, "CopyProperties");
            return dest;
        }

    }

}
