//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NetObjTypeData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.NetObjType> CopyProperties(ICollection<NetObjTypeData> orig, ICollection<CyberpunkServer.Models.NetObjType> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.NetObjType> dictionary1 = new Dictionary<int, CyberpunkServer.Models.NetObjType>();
                Dictionary<int, NetObjTypeData> dictionary2 = new Dictionary<int, NetObjTypeData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        NetObjTypeData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.NetObjType();
                        dest.Add(NetObjTypeData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.NetObjType> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<NetObjTypeData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator NetObjTypeData(CyberpunkServer.Models.NetObjType NetObjType)
        {
            var ret = Converter<NetObjTypeData, Models.NetObjType>.ConvertType(NetObjType, new NetObjTypeData());
            return ret;
        }

        public static List<NetObjTypeData> ConvertList(ICollection<CyberpunkServer.Models.NetObjType> origs)
        {

            var ret = Converter<NetObjTypeData, NetObjType>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.NetObjType CopyProperties(NetObjTypeData NetObjType, Models.NetObjType dest, CyberpunkEntities db)
        {
            Converter<NetObjTypeData, NetObjType>.ConvertType<NetObjTypeData>(NetObjType, dest, "CopyProperties");
            return dest;
        }

    }
}
