//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;
    public partial class PlayerSkillData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerSkill> CopyProperties(ICollection<PlayerSkillData> orig, ICollection<CyberpunkServer.Models.PlayerSkill> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerSkill> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerSkill>();
                Dictionary<int, PlayerSkillData> dictionary2 = new Dictionary<int, PlayerSkillData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerSkillData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerSkill();
                        dest.Add(PlayerSkillData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerSkill> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerSkillData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerSkillData(CyberpunkServer.Models.PlayerSkill PlayerSkill)
        {
            var ret = Converter<PlayerSkillData, Models.PlayerSkill>.ConvertType(PlayerSkill, new PlayerSkillData());
            return ret;
        }

        public static List<PlayerSkillData> ConvertList(ICollection<CyberpunkServer.Models.PlayerSkill> origs)
        {

            var ret = Converter<PlayerSkillData, PlayerSkill>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerSkill CopyProperties(PlayerSkillData PlayerSkill, Models.PlayerSkill dest, CyberpunkEntities db)
        {
            Converter<PlayerSkillData, PlayerSkill>.ConvertType<PlayerSkillData>(PlayerSkill, dest, "CopyProperties");
            return dest;
        }

    }
}
