//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace CyberpunkServer.Models.DTO
{
    public partial class PlayerComputerProgramsData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerComputerPrograms> CopyProperties(ICollection<PlayerComputerProgramsData> orig, ICollection<CyberpunkServer.Models.PlayerComputerPrograms> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerComputerPrograms> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerComputerPrograms>();
                Dictionary<int, PlayerComputerProgramsData> dictionary2 = new Dictionary<int, PlayerComputerProgramsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerComputerProgramsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerComputerPrograms();
                        dest.Add(PlayerComputerProgramsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerComputerPrograms> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerComputerProgramsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerComputerProgramsData(CyberpunkServer.Models.PlayerComputerPrograms PlayerComputerPrograms)
        {
            var ret = Converter<PlayerComputerProgramsData, Models.PlayerComputerPrograms>.ConvertType(PlayerComputerPrograms, new PlayerComputerProgramsData());
            return ret;
        }

        public static List<PlayerComputerProgramsData> ConvertList(ICollection<CyberpunkServer.Models.PlayerComputerPrograms> origs)
        {

            var ret = Converter<PlayerComputerProgramsData, PlayerComputerPrograms>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerComputerPrograms CopyProperties(PlayerComputerProgramsData PlayerComputerPrograms, Models.PlayerComputerPrograms dest, CyberpunkEntities db)
        {
            Converter<PlayerComputerProgramsData, PlayerComputerPrograms>.ConvertType<PlayerComputerProgramsData>(PlayerComputerPrograms, dest, "CopyProperties");
            return dest;
        }


    }
}