//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models
{
    using CyberpunkServer.Models.DTO;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlayerCyberdeckImprovementsData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerCyberdeckImprovements> CopyProperties(ICollection<PlayerCyberdeckImprovementsData> orig, ICollection<CyberpunkServer.Models.PlayerCyberdeckImprovements> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerCyberdeckImprovements> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerCyberdeckImprovements>();
                Dictionary<int, PlayerCyberdeckImprovementsData> dictionary2 = new Dictionary<int, PlayerCyberdeckImprovementsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerCyberdeckImprovementsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerCyberdeckImprovements();
                        dest.Add(PlayerCyberdeckImprovementsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerCyberdeckImprovements> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerCyberdeckImprovementsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerCyberdeckImprovementsData(CyberpunkServer.Models.PlayerCyberdeckImprovements PlayerCyberdeckImprovements)
        {
            var ret = Converter<PlayerCyberdeckImprovementsData, Models.PlayerCyberdeckImprovements>.ConvertType(PlayerCyberdeckImprovements, new PlayerCyberdeckImprovementsData());
            return ret;
        }

        public static List<PlayerCyberdeckImprovementsData> ConvertList(ICollection<CyberpunkServer.Models.PlayerCyberdeckImprovements> origs)
        {

            var ret = Converter<PlayerCyberdeckImprovementsData, PlayerCyberdeckImprovements>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerCyberdeckImprovements CopyProperties(PlayerCyberdeckImprovementsData PlayerCyberdeckImprovements, Models.PlayerCyberdeckImprovements dest, CyberpunkEntities db)
        {
            Converter<PlayerCyberdeckImprovementsData, PlayerCyberdeckImprovements>.ConvertType<PlayerCyberdeckImprovementsData>(PlayerCyberdeckImprovements, dest, "CopyProperties");
            return dest;
        }


    }
}