//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;

    public partial class PlayerCyberneticsData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerCybernetics> CopyProperties(ICollection<PlayerCyberneticsData> orig, ICollection<CyberpunkServer.Models.PlayerCybernetics> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerCybernetics> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerCybernetics>();
                Dictionary<int, PlayerCyberneticsData> dictionary2 = new Dictionary<int, PlayerCyberneticsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerCyberneticsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerCybernetics();
                        dest.Add(PlayerCyberneticsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerCybernetics> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerCyberneticsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerCyberneticsData(CyberpunkServer.Models.PlayerCybernetics PlayerCybernetics)
        {
            var ret = Converter<PlayerCyberneticsData, Models.PlayerCybernetics>.ConvertType(PlayerCybernetics, new PlayerCyberneticsData());
            return ret;
        }

        public static List<PlayerCyberneticsData> ConvertList(ICollection<CyberpunkServer.Models.PlayerCybernetics> origs)
        {

            var ret = Converter<PlayerCyberneticsData, PlayerCybernetics>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerCybernetics CopyProperties(PlayerCyberneticsData PlayerCybernetics, Models.PlayerCybernetics dest, CyberpunkEntities db)
        {
            Converter<PlayerCyberneticsData, PlayerCybernetics>.ConvertType<PlayerCyberneticsData>(PlayerCybernetics, dest, "CopyProperties");
            return dest;
        }

    }
}
