//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace CyberpunkServer.Models.DTO
{
    public partial class PlayerComputerImprovementsData:iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerComputerImprovements> CopyProperties(ICollection<PlayerComputerImprovementsData> orig, ICollection<CyberpunkServer.Models.PlayerComputerImprovements> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerComputerImprovements> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerComputerImprovements>();
                Dictionary<int, PlayerComputerImprovementsData> dictionary2 = new Dictionary<int, PlayerComputerImprovementsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerComputerImprovementsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerComputerImprovements();
                        dest.Add(PlayerComputerImprovementsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerComputerImprovements> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerComputerImprovementsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerComputerImprovementsData(CyberpunkServer.Models.PlayerComputerImprovements PlayerComputerImprovements)
        {
            var ret = Converter<PlayerComputerImprovementsData, Models.PlayerComputerImprovements>.ConvertType(PlayerComputerImprovements, new PlayerComputerImprovementsData());
            return ret;
        }

        public static List<PlayerComputerImprovementsData> ConvertList(ICollection<CyberpunkServer.Models.PlayerComputerImprovements> origs)
        {

            var ret = Converter<PlayerComputerImprovementsData, PlayerComputerImprovements>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerComputerImprovements CopyProperties(PlayerComputerImprovementsData PlayerComputerImprovements, Models.PlayerComputerImprovements dest, CyberpunkEntities db)
        {
            Converter<PlayerComputerImprovementsData, PlayerComputerImprovements>.ConvertType<PlayerComputerImprovementsData>(PlayerComputerImprovements, dest, "CopyProperties");
            return dest;
        }


    }
}