//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;

    public partial class PlayerWeaponData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.PlayerWeapon> CopyProperties(ICollection<PlayerWeaponData> orig, ICollection<CyberpunkServer.Models.PlayerWeapon> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.PlayerWeapon> dictionary1 = new Dictionary<int, CyberpunkServer.Models.PlayerWeapon>();
                Dictionary<int, PlayerWeaponData> dictionary2 = new Dictionary<int, PlayerWeaponData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        PlayerWeaponData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.PlayerWeapon();
                        dest.Add(PlayerWeaponData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.PlayerWeapon> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<PlayerWeaponData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator PlayerWeaponData(CyberpunkServer.Models.PlayerWeapon PlayerWeapon)
        {
            var ret = Converter<PlayerWeaponData, Models.PlayerWeapon>.ConvertType(PlayerWeapon, new PlayerWeaponData());
            return ret;
        }

        public static List<PlayerWeaponData> ConvertList(ICollection<CyberpunkServer.Models.PlayerWeapon> origs)
        {

            var ret = Converter<PlayerWeaponData, PlayerWeapon>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.PlayerWeapon CopyProperties(PlayerWeaponData PlayerWeapon, Models.PlayerWeapon dest, CyberpunkEntities db)
        {
            Converter<PlayerWeaponData, PlayerWeapon>.ConvertType<PlayerWeaponData>(PlayerWeapon, dest, "CopyProperties");
            return dest;
        }

    }
}