//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProgramData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.Program> CopyProperties(ICollection<ProgramData> orig, ICollection<CyberpunkServer.Models.Program> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.Program> dictionary1 = new Dictionary<int, CyberpunkServer.Models.Program>();
                Dictionary<int, ProgramData> dictionary2 = new Dictionary<int, ProgramData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        ProgramData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.Program();
                        dest.Add(ProgramData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.Program> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<ProgramData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator ProgramData(CyberpunkServer.Models.Program Program)
        {
            var ret = Converter<ProgramData, Models.Program>.ConvertType(Program, new ProgramData());
            return ret;
        }

        public static List<ProgramData> ConvertList(ICollection<CyberpunkServer.Models.Program> origs)
        {

            var ret = Converter<ProgramData, Program>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.Program CopyProperties(ProgramData Program, Models.Program dest, CyberpunkEntities db)
        {
            Converter<ProgramData, Program>.ConvertType<ProgramData>(Program, dest, "CopyProperties");
            return dest;
        }

    }
}