//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProgramTypeData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.ProgramType> CopyProperties(ICollection<ProgramTypeData> orig, ICollection<CyberpunkServer.Models.ProgramType> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.ProgramType> dictionary1 = new Dictionary<int, CyberpunkServer.Models.ProgramType>();
                Dictionary<int, ProgramTypeData> dictionary2 = new Dictionary<int, ProgramTypeData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        ProgramTypeData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.ProgramType();
                        dest.Add(ProgramTypeData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.ProgramType> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<ProgramTypeData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator ProgramTypeData(CyberpunkServer.Models.ProgramType ProgramType)
        {
            var ret = Converter<ProgramTypeData, Models.ProgramType>.ConvertType(ProgramType, new ProgramTypeData());
            return ret;
        }

        public static List<ProgramTypeData> ConvertList(ICollection<CyberpunkServer.Models.ProgramType> origs)
        {

            var ret = Converter<ProgramTypeData, ProgramType>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.ProgramType CopyProperties(ProgramTypeData ProgramType, Models.ProgramType dest, CyberpunkEntities db)
        {
            Converter<ProgramTypeData, ProgramType>.ConvertType<ProgramTypeData>(ProgramType, dest, "CopyProperties");
            return dest;
        }

    }
}