//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SkillTypesData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.SkillTypes> CopyProperties(ICollection<SkillTypesData> orig, ICollection<CyberpunkServer.Models.SkillTypes> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.SkillTypes> dictionary1 = new Dictionary<int, CyberpunkServer.Models.SkillTypes>();
                Dictionary<int, SkillTypesData> dictionary2 = new Dictionary<int, SkillTypesData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        SkillTypesData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.SkillTypes();
                        dest.Add(SkillTypesData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.SkillTypes> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<SkillTypesData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator SkillTypesData(CyberpunkServer.Models.SkillTypes SkillTypes)
        {
            var ret = Converter<SkillTypesData, Models.SkillTypes>.ConvertType(SkillTypes, new SkillTypesData());
            return ret;
        }

        public static List<SkillTypesData> ConvertList(ICollection<CyberpunkServer.Models.SkillTypes> origs)
        {

            var ret = Converter<SkillTypesData, SkillTypes>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.SkillTypes CopyProperties(SkillTypesData SkillTypes, Models.SkillTypes dest, CyberpunkEntities db)
        {
            Converter<SkillTypesData, SkillTypes>.ConvertType<SkillTypesData>(SkillTypes, dest, "CopyProperties");
            return dest;
        }

    }
}