//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UnitsData : iConvert
    {
        public static ICollection<CyberpunkServer.Models.Units> CopyProperties(ICollection<UnitsData> orig, ICollection<CyberpunkServer.Models.Units> dest, CyberpunkEntities db)
        {
            if (orig.Any())
            {
                Dictionary<int, CyberpunkServer.Models.Units> dictionary1 = new Dictionary<int, CyberpunkServer.Models.Units>();
                Dictionary<int, UnitsData> dictionary2 = new Dictionary<int, UnitsData>();
                if (dest.Any())
                {
                    foreach (var obj in dest)
                        dictionary1.Add(obj.id, obj);
                }
                foreach (var orig1 in orig)
                {
                    if (dictionary1.ContainsKey(orig1.id))
                    {
                        var dest1 = dictionary1[orig1.id];
                        UnitsData.CopyProperties(orig1, dest1, db);
                    }
                    else
                    {
                        var dest2 = new Models.Units();
                        dest.Add(UnitsData.CopyProperties(orig1, dest2, db));
                    }
                    if (orig1.id != 0)
                    {
                        dictionary2.Add(orig1.id, orig1);
                    }
                }
                foreach (KeyValuePair<int, Models.Units> keyValuePair in dictionary1)
                {
                    if (!dictionary2.ContainsKey(keyValuePair.Key))
                        dest.Remove(keyValuePair.Value);
                }
            }
            else if (dest != null && !orig.Any<UnitsData>())
                dest.Clear();
            return dest;
        }
        public static explicit operator UnitsData(CyberpunkServer.Models.Units Units)
        {
            var ret = Converter<UnitsData, Models.Units>.ConvertType(Units, new UnitsData());
            return ret;
        }

        public static List<UnitsData> ConvertList(ICollection<CyberpunkServer.Models.Units> origs)
        {

            var ret = Converter<UnitsData, Units>.ConvertList(origs);
            return ret;
        }

        public static CyberpunkServer.Models.Units CopyProperties(UnitsData Units, Models.Units dest, CyberpunkEntities db)
        {
            Converter<UnitsData, Units>.ConvertType<UnitsData>(Units, dest, "CopyProperties");
            return dest;
        }


    }
}