//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;

    public partial class CyberneticsData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CyberneticsData()
        {
            this.PlayerCybernetics = new HashSet<PlayerCyberneticsData>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumDice { get; set; }
        public Nullable<int> DiceType { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<int> HL { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> SurgType { get; set; }
        public string Description { get; set; }
    
        public virtual SurgicalCodeData SurgicalCode { get; set; }
        public virtual CyberneticTypesData CyberneticTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCyberneticsData> PlayerCybernetics { get; set; }
    }
}
