//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlayerWeaponData
    {

		public int id { get; set; }

		public int? PlayerID { get; set; }

		public string? Name { get; set; }

		public int? NumDice { get; set; }

		public int? DiceType { get; set; }

		public int? Bonus { get; set; }

		public int? ROF { get; set; }

		public int? REL { get; set; }

		public int? Type { get; set; }

		public int? Conc { get; set; }

		public int? Shots1 { get; set; }

		public int? Shots2 { get; set; }

		public int? Range { get; set; }

		public string? Description { get; set; }

		public virtual WeaponConcTypesData? ConcNavigation { get; set; }

		public virtual WeaponTypesData? TypeNavigation 
		{
			get;
			set;
		}
       
    }
}
