//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class PlayerSkillData
    {
        public PlayerSkillData()
        {
            this.PlayerSkillModifiers = new List<PlayerSkillModifiersData>();
        }
		public int id { get; set; }

		public int Ranks { get; set; }

		public int Bonus { get; set; }

		public int CurrentIP { get; set; }

		public int? PlayerID { get; set; }

		public int? SkillID { get; set; }

		public string? Name { get; set; }

		public bool IsCustom { get; set; }

		public bool IsChipped { get; set; }

		public virtual SkillData Skill { get; set; }
        public virtual List<PlayerSkillModifiersData> PlayerSkillModifiers { get; set; }


    }
}
