//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramData
    {
        
        public ProgramData()
        {
            this.ProgramFunction = new List<ProgramFunctionsData>();
            this.ProgramOptions = new List<ProgramOptionsData>();
            this.Subroutines = new List<ProgramData>();
        }

        public int id { get; set; }
        public string name { get; set; }
        public int Strength { get; set; }
        public Nullable<int> ProgramTypeID { get; set; }
        public double cost { get; set; }
        public int MU { get; set; }
        public string Description { get; set; }

        public virtual ProgramTypeData ProgramType { get; set; }
        public virtual List<ProgramFunctionsData> ProgramFunction { get; set; }
        public virtual List<ProgramOptionsData> ProgramOptions { get; set; }
        public virtual List<ProgramData> Subroutines { get; set; }
        public List<ProgramData> SubProgram
		{
            get
            {
                return Subroutines;
            }
            set
            {
                Subroutines = value;
            }
        }
    }
}
