//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;

    public partial class SubgridData
    {
        
        public SubgridData()
        {
            this.Fortress = new List<FortressData>();
            this.JackedInPlayers=new List<PlayerData>();
        }
    
        public int id { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public string Name { get; set; }
        public string UserID { get; set; }

        
        public virtual List<FortressData> Fortress { get; set; }
        public List<PlayerData> JackedInPlayers { get; set; }
    }
}
