//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerPeripheralsData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComputerPeripheralsData()
        {
            this.ComputerPeripheralSkillModifiers = new List<ComputerPeripheralSkillModifiersData>();
            this.ComputerPeripheralStatModifiers = new List<ComputerPeripheralStatModifiersData>();
        }

        public int id { get; set; }
        public string name { get; set; }
        public double CostPerUnitLow { get; set; }
        public double CostPerUnitHigh { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public Nullable<int> MU { get; set; }
        public Nullable<int> Bonus { get; set; }
        public string Description { get; set; }


        public virtual List<ComputerPeripheralSkillModifiersData> ComputerPeripheralSkillModifiers { get; set; }
        
        public virtual List<ComputerPeripheralStatModifiersData> ComputerPeripheralStatModifiers { get; set; }
        public virtual UnitsData Units1 { get; set; }
        
    }
}
