//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberpunkServer.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FortressSkillsData
    {
        public int id { get; set; }
        public int FortressID { get; set; }
        public int SkillID { get; set; }
        public Nullable<int> Ranks { get; set; }
    
        public virtual FortressData Fortress { get; set; }
        public virtual SkillData Skill { get; set; }
    }
}
