//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CyberpunkServer.Models.DTO;
using System;
public interface iDevicePrograms
{
	bool Rezzed { get; set; }
	bool Packed { get; set; }
	int Strength { get; set; }
	ProgramData Program { get; set; }
	int MU { get; }
}

namespace CyberpunkServer.Models.DTO
{
    public partial class PlayerCyberdeckProgramsData: iDevicePrograms
	{
        public int id { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> PlayerCyberdeckID { get; set; }
        public bool Rezzed { get; set; }
        public bool Packed { get; set; }
        public int Strength { get; set; }
        public virtual ProgramData Program { get; set; }
        public int MU
        {
            get
            {
                return Convert.ToInt32(Program.MU * (Packed ? 0.5 : 1));
            }
        }

    }
}